AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: WebSpider Cloudformation.
Resources:
  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./nodejs/
      CompatibleRuntimes:
        - nodejs18.x  # Adjust this based on your Lambda function runtime
      Description: Node Modules for Webspider(axios,cheerio,aws-sdk)

  WebspiderRootLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.webSpider_AmazonSQS
      Runtime: nodejs18.x
      CodeUri: .
      Description: WespiderRoot Function
      MemorySize: 128
      Timeout: 30
      Layers:
        - !Ref NodeModulesLayer
    Policies:
      - SQSSendMessagePolicy:
          QueueName:
            !GetAtt webSpiderQueue.QueueName        

  WebspiderSqsReceive:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: sqsReceiveMesg.sqsReceiveMessage
      Runtime: nodejs18.x
      CodeUri: .
      Description: Wespider SQS Function
      MemorySize: 128
      Timeout: 30
      Layers:
        - !Ref NodeModulesLayer
    Policies:
      - SQSSendMessagePolicy:
          QueueName:
            !GetAtt webSpiderQueue.QueueName
      - SQSPollerPolicy:
          QueueName:
            !GetAtt webSpiderQueue.QueueName            
                    

  webSpiderQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: webSpiderQueue
      VisibilityTimeout: 30
