AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: WebSpider Cloudformation.

Resources:
  WebspiderRootLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: .
      Description: Webspider Root Function
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          region: !Ref AWS::Region
          queueUrl: !GetAtt SQSQueue1.QueueUrl
      Layers:
        - arn:aws:lambda:us-east-1:201814457761:layer:AWS-SDK-NodeModules:1
        - arn:aws:lambda:us-east-1:201814457761:layer:WebSpider-Nodemodules:1
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt SQSQueue1.Arn   

  WebspiderSqsReceive:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: sqsReceiveMesg.handler
      Runtime: nodejs18.x
      CodeUri: .
      Description: Webspider SQS Function
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          region: !Ref AWS::Region
          queueUrl: !GetAtt SQSQueue1.QueueUrl
      Layers:
        - arn:aws:lambda:us-east-1:201814457761:layer:AWS-SDK-NodeModules:1
        - arn:aws:lambda:us-east-1:201814457761:layer:WebSpider-Nodemodules:1
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
                - sqs:DeleteMessage
                - sqs:ReceiveMessage
              Resource: !GetAtt SQSQueue1.Arn

  SQSQueue1:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: webSpiderQueue
      VisibilityTimeout: 30
      SqsManagedSseEnabled: true

  