AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: WebSpider Cloudformation.
Resources:
  WebspiderRootLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: s3://sam-fahad-nodejs/28e9dbcd77742a883d7edbf5af18fac4
      Description: WespiderRoot Function
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          region:
            Ref: AWS::Region
          queueUrl:
            Fn::GetAtt:
            - SQSQueue1
            - QueueUrl
      Layers:
      - arn:aws:lambda:us-east-1:201814457761:layer:AWS-SDK-NodeModules:1
      - arn:aws:lambda:us-east-1:201814457761:layer:WebSpider-Nodemodules:1
    Policies:
    - SQSSendMessagePolicy:
        QueueName:
          Fn::GetAtt:
          - webSpiderQueue
          - QueueName
  WebspiderSqsReceive:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sqsReceiveMesg.handler
      Runtime: nodejs18.x
      CodeUri: s3://sam-fahad-nodejs/28e9dbcd77742a883d7edbf5af18fac4
      Description: Wespider SQS Function
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          region:
            Ref: AWS::Region
          queueUrl:
            Fn::GetAtt:
            - SQSQueue1
            - QueueUrl
      Layers:
      - arn:aws:lambda:us-east-1:201814457761:layer:AWS-SDK-NodeModules:1
      - arn:aws:lambda:us-east-1:201814457761:layer:WebSpider-Nodemodules:1
    Policies:
    - SQSSendMessagePolicy:
        QueueName:
          Fn::GetAtt:
          - SQSQueue1
          - QueueName
    - SQSPollerPolicy:
        QueueName:
          Fn::GetAtt:
          - SQSQueue1
          - QueueName
  SQSQueue1:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: webSpiderQueue
      VisibilityTimeout: 30
      SqsManagedSseEnabled: true
